<!-- kv3 encoding:text:version{e21c7f3c-8a33-41c5-9977-a76d3a32aa0d} format:generic:version{7412167c-06e9-4698-aff2-e63eb59037e7} -->
{
	data = 
	{
		id = "scientist"
		displayname = "Scientist"
		model = resource:"models/citizen/citizen.vmdl"
		description = "You are a scientist"
		maxplayers = 10
		salary = 60
		category = "default"
		sortorder = 1
		stamina = "0.2"
		walkspeed = "50"
		sprintspeed = "220"
		defaultspeed = "140"
	}
}